/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2019-05-24 08:53:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Demo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<HTML>\r\n");
      out.write("<HEAD>\r\n");
      out.write("<TITLE>Add/Remove dynamic rows in HTML table</TITLE>\r\n");
      out.write("<SCRIPT language=\"javascript\">\r\n");
      out.write("\tvar count = 1;\r\n");
      out.write("\tfunction addRow(tableID, x) {\r\n");
      out.write("\t\tif (count < x) {\r\n");
      out.write("\t\t\tvar table = document.getElementById(tableID);\r\n");
      out.write("\t\t\tvar rowCount = table.rows.length;\r\n");
      out.write("\t\t\tvar row = table.insertRow(rowCount);\r\n");
      out.write("\t\t\tvar colCount = table.rows[0].cells.length;\r\n");
      out.write("\t\t\tfor (var i = 0; i < colCount; i++) {\r\n");
      out.write("\t\t\t\tvar newcell = row.insertCell(i);\r\n");
      out.write("\t\t\t\tnewcell.innerHTML = table.rows[0].cells[i].innerHTML;\r\n");
      out.write("\t\t\t\t//alert(newcell.childNodes);\r\n");
      out.write("\t\t\t\tswitch (newcell.childNodes[0].type) {\r\n");
      out.write("\t\t\t\tcase \"text\":\r\n");
      out.write("\t\t\t\t\tnewcell.childNodes[0].value = \"\";\r\n");
      out.write("\t\t\t\t\tnewcell.childNodes[0].name = \"name\" + count;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"checkbox\":\r\n");
      out.write("\t\t\t\t\tnewcell.childNodes[0].checked = false;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"date\":\r\n");
      out.write("\t\t\t\t\tnewcell.childNodes[3].selectedIndex = 0;\r\n");
      out.write("\t\t\t\t\tnewcell.childNodes[3].name = \"gender\" + count;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcount++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction deleteRow(tableID) {\r\n");
      out.write("\t\ttry {\r\n");
      out.write("\t\t\tcount--;\r\n");
      out.write("\t\t\tvar table = document.getElementById(tableID);\r\n");
      out.write("\t\t\tvar rowCount = table.rows.length;\r\n");
      out.write("\t\t\tfor (var i = 0; i < rowCount; i++) {\r\n");
      out.write("\t\t\t\tvar row = table.rows[i];\r\n");
      out.write("\t\t\t\tvar chkbox = row.cells[0].childNodes[0];\r\n");
      out.write("\t\t\t\tif (null != chkbox && true == chkbox.checked) {\r\n");
      out.write("\t\t\t\t\tif (rowCount <= 1) {\r\n");
      out.write("\t\t\t\t\t\talert(\"Cannot delete all the rows.\");\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\ttable.deleteRow(i);\r\n");
      out.write("\t\t\t\t\trowCount--;\r\n");
      out.write("\t\t\t\t\ti--;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} catch (e) {\r\n");
      out.write("\t\t\talert(e);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</HEAD>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: Times New Roman, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".display .display {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 10%;\r\n");
      out.write("\tleft: 22%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-image: url(\"Airline-Header.jpg\");\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\theight: 600px;\r\n");
      out.write("\tbackground-position: center;\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero-content {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 10%;\r\n");
      out.write("\tleft: 97%;\r\n");
      out.write("\ttransform: translate(-50%, -50%);\r\n");
      out.write("\tcolor: green;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero-context {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\ttransform: translate(-50%, -50%);\r\n");
      out.write("\tcolor: green;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero-con {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 160%;\r\n");
      out.write("\tleft: 60%;\r\n");
      out.write("\ttransform: translate(-50%, -50%);\r\n");
      out.write("\tcolor: green;\r\n");
      out.write("\tsize: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-default {\r\n");
      out.write("\tbackground: #000;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-default:hover {\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topnav {\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tbackground-color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topnav a {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tcolor: #f2f2f2;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 15px 20px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topnav a:hover {\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topnav a.active {\r\n");
      out.write("\tbackground-color: #4CAF50;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topnav-right {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: Times New Roman, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".display .display {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 10%;\r\n");
      out.write("\tleft: 22%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-image: url(\"flgphoto.jpg\");\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\theight: 600px;\r\n");
      out.write("\tbackground-position: center;\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero-content {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 2%;\r\n");
      out.write("\tleft: 96%;\r\n");
      out.write("\ttransform: translate(-50%, -50%);\r\n");
      out.write("\tcolor: green;\r\n");
      out.write("}\r\n");
      out.write(".hero-back{\r\n");
      out.write("\ttxt-align: center;\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\ttop: 2%;\r\n");
      out.write("\tleft: 90%;\r\n");
      out.write("\ttransform: translate(-50%, -50%);\r\n");
      out.write("\tcolor: green;\r\n");
      out.write("}\r\n");
      out.write(".hero-context {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\ttransform: translate(-50%, -50%);\r\n");
      out.write("\tcolor: green;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero-con {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 45%;\r\n");
      out.write("\tleft: 15%;\r\n");
      out.write("\ttransform: translate(-50%, -50%);\r\n");
      out.write("\tcolor: green;\r\n");
      out.write("\tsize: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-default {\r\n");
      out.write("\tbackground: #000;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-default:hover {\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topnav {\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tbackground-color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topnav a {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tcolor: #f2f2f2;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 15px 56.5px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tbackground-color: grey;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topnav a:hover {\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topnav a.active {\r\n");
      out.write("\tbackground-color: #4CAF50;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topnav-right {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<BODY>\r\n");
      out.write("\t<div class=\"hero-page\">\r\n");
      out.write("\t\t<h4>\r\n");
      out.write("\t\t\t<b>&nbsp;&nbsp;It is the largest airline in India by\r\n");
      out.write("\t\t\t\tfleet size and\r\n");
      out.write("\t\t\t\tdestinations!!&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Customer\r\n");
      out.write("\t\t\t\tService:080 4666 2222\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\tContact: airlineservice@airlines.com</b>\r\n");
      out.write("\t\t</h4>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"topnav\">\r\n");
      out.write("\t\t<a class=\"active-non\" href=\"menupage.jsp\">Home <span\r\n");
      out.write("\t\t\tclass=\"sr-only\">(current)</span>\r\n");
      out.write("\t\t</a> <a class=\"active-non\" href=\"flightsearch.jsp\">Available\r\n");
      out.write("\t\t\tFlights</a> <a class=\"active\" href=\"singletrip.jsp\">New ticket\r\n");
      out.write("\t\t\tBooking</a>\r\n");
      out.write("\t\t<!-- <div class=\"topnav-right\"> -->\r\n");
      out.write("\t\t<a class=\"active-non\" href=\"ticketstatus.jsp\">Ticket Status</a> <a\r\n");
      out.write("\t\t\tclass=\"active-non\" href=\"cancelticket.jsp\">Cancel Ticket</a> <a\r\n");
      out.write("\t\t\tclass=\"active-non\" href=\"support.jsp\">Support Details</a>\r\n");
      out.write("\t\t<!-- </div> -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"hero-text\">\r\n");
      out.write("\t\t<h3>\r\n");
      out.write("\t\t\t<left> <b>Enter the valid details of Passengers:</b></left>\r\n");
      out.write("\t\t</h3>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<form method=\"post\" action=\"AddPassengersServlet\">\r\n");
      out.write("\t\t\t<INPUT type=\"button\" value=\"Add Row\"\r\n");
      out.write("\t\t\t\tonclick=\"addRow('dataTable','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalTravelpassengers }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("')\" /> <INPUT\r\n");
      out.write("\t\t\t\ttype=\"button\" value=\"Delete Row\" onclick=\"deleteRow('dataTable')\" />\r\n");
      out.write("\t\t\t<TABLE id=\"dataTable\" width=\"350px\" border=\"2\">\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD><INPUT type=\"checkbox\" name=\"chk\" /></TD>\r\n");
      out.write("\t\t\t\t\t<td style=\"color: black\"><b>Name:</b></td>\r\n");
      out.write("\t\t\t\t\t<TD><INPUT type=\"text\" name=\"name0\" /></TD>\r\n");
      out.write("\t\t\t\t\t<!-- <td style=\"color: black\"><b>Age:</b></td> -->\r\n");
      out.write("\t\t\t\t\t<!-- <TD><INPUT type=\"text\" name=\"age\" /></TD> -->\r\n");
      out.write("\t\t\t\t\t<TD><input type=\"date\" style=\"display: none\"><b>Gender:</b>\r\n");
      out.write("\t\t\t\t\t\t<SELECT name=\"gender0\">\r\n");
      out.write("\t\t\t\t\t\t\t<OPTION value=\"male\">Male</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t<OPTION value=\"female\">Female</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t<OPTION value=\"others\">Others</OPTION>\r\n");
      out.write("\t\t\t\t\t</SELECT></TD>\r\n");
      out.write("\t\t\t\t\t<!-- <td class=\"select\"><b>Gender:&nbsp;&nbsp;&nbsp;&nbsp;</b></td>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"Gender\">\r\n");
      out.write("\t\t\t\t\t\t\t<OPTION value=\"male\">Male</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t<OPTION value=\"female\">Female</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t<OPTION value=\"others\">Others</OPTION>\r\n");
      out.write("\t\t\t\t\t</select></td> -->\r\n");
      out.write("\t\t\t\t\t<!-- <td><a href=\"passengersubmit.jsp\">submit</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t -->\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-info\" style=\"width: 120px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>SUBMIT</b>\r\n");
      out.write("\t\t\t\t\t\t\t</button> <br>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<div class=\"hero-content\">\r\n");
      out.write("\t\t\t<a href=\"index.jsp\" class=\"btn btn-info\" role=\"button\">LOGOUT</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"hero-back\">\r\n");
      out.write("\t\t\t\t<a href=\"passengersnumber.jsp\" class=\"btn btn-info\" role=\"button\">BACK</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
