/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2019-05-24 08:53:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<!-- <link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script> -->\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<style>\n");
      out.write(".display {\n");
      out.write("\tposition: absolute;\n");
      out.write("\ttop: 37%;\n");
      out.write("\tleft: 22%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body {\n");
      out.write("\tmargin: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".hero-image {\n");
      out.write("\tbackground-image: url(\"profile.bmp\");\n");
      out.write("\theight: 600px;\n");
      out.write("\tbackground-position: center;\n");
      out.write("\tbackground-repeat: no-repeat;\n");
      out.write("\tbackground-size: cover;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".hero-print {\n");
      out.write("\ttext-align: center;\n");
      out.write("\tposition: absolute;\n");
      out.write("\ttop: 150%;\n");
      out.write("\tleft: 20%;\n");
      out.write("\ttransform: translate(-50%, -50%);\n");
      out.write("\tcolor: green;\n");
      out.write("\tfont-size: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".hero-text {\n");
      out.write("\ttext-align: center;\n");
      out.write("\tposition: absolute;\n");
      out.write("\ttop: 50%;\n");
      out.write("\tleft: 80%;\n");
      out.write("\ttransform: translate(-50%, -50%);\n");
      out.write("\tcolor: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".hero-content {\n");
      out.write("\ttext-align: center;\n");
      out.write("\tposition: absolute;\n");
      out.write("\ttop: 120%;\n");
      out.write("\tleft: 60%;\n");
      out.write("\ttransform: translate(-50%, -50%);\n");
      out.write("\tcolor: green;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title-text {\n");
      out.write("\ttext-align: center;\n");
      out.write("\tposition: absolute;\n");
      out.write("\ttop: 5%;\n");
      out.write("\tleft: 50%;\n");
      out.write("\ttransform: translate(-50%, -50%);\n");
      out.write("\tcolor: red;\n");
      out.write("}\n");
      out.write("\n");
      out.write("form {\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn-default {\n");
      out.write("\tbackground: #000;\n");
      out.write("\tcolor: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn-default:hover {\n");
      out.write("\tbackground: #fff;\n");
      out.write("\tcolor: #000;\n");
      out.write("}\n");
      out.write("\n");
      out.write("form {\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body style=\"font-family: Times New Roman; font-size: 19px\">\n");
      out.write("\t<div class=\"title-text\">\n");
      out.write("\t\t<!-- <h2>AIRLINE-BOOKING</h2> -->\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"hero-image\">\n");
      out.write("\t\t<div class=\"hero-text\">\n");
      out.write("\t\t\t<form method=\"post\" action=\"UserLoginServlet\">\n");
      out.write("\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t<tr align=\"center\">\n");
      out.write("\t\t\t\t\t\t\t<td style=\"color: black\" colspan=\"2\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t\t\t\t<b> LOGIN</b>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td>&nbsp;</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t<td style=\"color: black\"><b>Email-id:</b></td>\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"email\" required></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td>&nbsp;</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t<td style=\"color: black\"><b>Password:</b></td>\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"password\" name=\"password\" required></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t\t<div class=\"hero-content\">\n");
      out.write("\t\t\t\t\t<button type=\"submit\" style=\"width: 60px\" class=\"btn btn-info\"\n");
      out.write("\t\t\t\t\t\trole=\"button\">submit</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"hero-print\">\n");
      out.write("\t\t\t\t\t<label style=\"color: red\"><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ERROR}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</b></label>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
