--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FLIGHT_DETAILS
--------------------------------------------------------

  CREATE TABLE "HR"."FLIGHT_DETAILS" 
   (	"FLG_ID" NUMBER(6,0), 
	"FLG_NAME" VARCHAR2(20 BYTE), 
	"FLG_SOURCE" VARCHAR2(20 BYTE), 
	"FLG_DESTINATION" VARCHAR2(20 BYTE), 
	"FLG_JOURNEY_DATE" DATE, 
	"FLG_DEPARTURE_TIME" TIMESTAMP (6), 
	"FLG_ARRIVAL_TIME" TIMESTAMP (6), 
	"FLG_ADULT_TICKET" NUMBER(8,0), 
	"FLG_AVALIABLE_TICKET" NUMBER(3,0), 
	"FLG_CHILDREN_TICKET" NUMBER(8,0), 
	"FLG_BABY_TICKET" NUMBER(8,0), 
	"CREATED_BY" NUMBER(10,0), 
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_BY" NUMBER(10,0), 
	"MODIFIED_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.FLIGHT_DETAILS
SET DEFINE OFF;
Insert into HR.FLIGHT_DETAILS (FLG_ID,FLG_NAME,FLG_SOURCE,FLG_DESTINATION,FLG_JOURNEY_DATE,FLG_DEPARTURE_TIME,FLG_ARRIVAL_TIME,FLG_ADULT_TICKET,FLG_AVALIABLE_TICKET,FLG_CHILDREN_TICKET,FLG_BABY_TICKET,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (4444,'AIR ASIA','CHENNAI','COIMBATORE',to_date('15-05-19','DD-MM-RR'),to_timestamp('15-05-19 07:20:10.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),to_timestamp('16-05-19 01:20:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1000,40,500,100,4444,to_timestamp('14-05-19 11:54:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),4444,to_timestamp('14-05-19 01:30:40.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'));
Insert into HR.FLIGHT_DETAILS (FLG_ID,FLG_NAME,FLG_SOURCE,FLG_DESTINATION,FLG_JOURNEY_DATE,FLG_DEPARTURE_TIME,FLG_ARRIVAL_TIME,FLG_ADULT_TICKET,FLG_AVALIABLE_TICKET,FLG_CHILDREN_TICKET,FLG_BABY_TICKET,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (8888,'INDIGO','CHENNAI','COIMBATORE',to_date('23-05-19','DD-MM-RR'),to_timestamp('24-05-19 07:20:10.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),to_timestamp('23-05-19 01:20:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1000,49,500,100,4444,to_timestamp('22-05-19 11:54:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),4444,to_timestamp('22-05-19 01:30:40.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'));
Insert into HR.FLIGHT_DETAILS (FLG_ID,FLG_NAME,FLG_SOURCE,FLG_DESTINATION,FLG_JOURNEY_DATE,FLG_DEPARTURE_TIME,FLG_ARRIVAL_TIME,FLG_ADULT_TICKET,FLG_AVALIABLE_TICKET,FLG_CHILDREN_TICKET,FLG_BABY_TICKET,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (1234,'AIR INDIA','CHENNAI','COIMBATORE',to_date('25-05-19','DD-MM-RR'),to_timestamp('24-05-19 07:20:10.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),to_timestamp('23-05-19 01:20:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1000,99,500,100,4444,to_timestamp('22-05-19 11:54:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),4444,to_timestamp('22-05-19 01:30:40.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'));
--------------------------------------------------------
--  DDL for Index FLIGHT_ID_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."FLIGHT_ID_UK" ON "HR"."FLIGHT_DETAILS" ("FLG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FLIGHT_DETAILS
--------------------------------------------------------

  ALTER TABLE "HR"."FLIGHT_DETAILS" ADD CONSTRAINT "FLIGHT_ID_UK" UNIQUE ("FLG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."FLIGHT_DETAILS" MODIFY ("FLG_SOURCE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."FLIGHT_DETAILS" MODIFY ("FLG_DESTINATION" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."FLIGHT_DETAILS" MODIFY ("FLG_JOURNEY_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."FLIGHT_DETAILS" MODIFY ("FLG_DEPARTURE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."FLIGHT_DETAILS" MODIFY ("FLG_ARRIVAL_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."FLIGHT_DETAILS" MODIFY ("FLG_ADULT_TICKET" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."FLIGHT_DETAILS" MODIFY ("FLG_AVALIABLE_TICKET" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."FLIGHT_DETAILS" MODIFY ("FLG_CHILDREN_TICKET" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."FLIGHT_DETAILS" MODIFY ("FLG_BABY_TICKET" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."FLIGHT_DETAILS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."FLIGHT_DETAILS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."FLIGHT_DETAILS" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."FLIGHT_DETAILS" MODIFY ("MODIFIED_DATE" NOT NULL ENABLE);
