--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRAVEL_PASSENGERS
--------------------------------------------------------

  CREATE TABLE "HR"."TRAVEL_PASSENGERS" 
   (	"BOOK_ID" NUMBER(10,0), 
	"PASS_NAME" VARCHAR2(60 BYTE), 
	"PASS_GENDER" VARCHAR2(6 BYTE), 
	"FLIGHT_ID" NUMBER(10,0), 
	"USER_ID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.TRAVEL_PASSENGERS
SET DEFINE OFF;
Insert into HR.TRAVEL_PASSENGERS (BOOK_ID,PASS_NAME,PASS_GENDER,FLIGHT_ID,USER_ID) values (235000,'hari','male',8888,166);
Insert into HR.TRAVEL_PASSENGERS (BOOK_ID,PASS_NAME,PASS_GENDER,FLIGHT_ID,USER_ID) values (236234,'mani','male',8888,166);
Insert into HR.TRAVEL_PASSENGERS (BOOK_ID,PASS_NAME,PASS_GENDER,FLIGHT_ID,USER_ID) values (237468,'ram','male',8888,168);
Insert into HR.TRAVEL_PASSENGERS (BOOK_ID,PASS_NAME,PASS_GENDER,FLIGHT_ID,USER_ID) values (238702,'arjun','male',8888,168);
Insert into HR.TRAVEL_PASSENGERS (BOOK_ID,PASS_NAME,PASS_GENDER,FLIGHT_ID,USER_ID) values (242404,'hari','male',1234,169);
Insert into HR.TRAVEL_PASSENGERS (BOOK_ID,PASS_NAME,PASS_GENDER,FLIGHT_ID,USER_ID) values (243638,'mano','male',1234,169);
Insert into HR.TRAVEL_PASSENGERS (BOOK_ID,PASS_NAME,PASS_GENDER,FLIGHT_ID,USER_ID) values (239936,'hari','male',1234,169);
Insert into HR.TRAVEL_PASSENGERS (BOOK_ID,PASS_NAME,PASS_GENDER,FLIGHT_ID,USER_ID) values (241170,'mano','male',1234,169);
Insert into HR.TRAVEL_PASSENGERS (BOOK_ID,PASS_NAME,PASS_GENDER,FLIGHT_ID,USER_ID) values (244872,'hari','male',1234,170);
Insert into HR.TRAVEL_PASSENGERS (BOOK_ID,PASS_NAME,PASS_GENDER,FLIGHT_ID,USER_ID) values (246106,'hari','male',1234,173);
Insert into HR.TRAVEL_PASSENGERS (BOOK_ID,PASS_NAME,PASS_GENDER,FLIGHT_ID,USER_ID) values (247340,'mano','male',1234,173);
--------------------------------------------------------
--  Constraints for Table TRAVEL_PASSENGERS
--------------------------------------------------------

  ALTER TABLE "HR"."TRAVEL_PASSENGERS" MODIFY ("PASS_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRAVEL_PASSENGERS" MODIFY ("PASS_GENDER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRAVEL_PASSENGERS" ADD CONSTRAINT "TRAVALLER_GENDER" CHECK (pass_gender='male' or pass_gender='female' or pass_gender='others') ENABLE;
